# Generated by Django 3.1.7 on 2021-05-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Joindate',
            field=models.DateField(default=datetime.date(2021, 5, 4)),
        ),
        migrations.AlterField(
            model_name='user',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
