# Generated by Django 3.1.7 on 2021-05-05 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20210504_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Joindate',
        ),
        migrations.AddField(
            model_name='user',
            name='joindate',
            field=models.DateField(default=datetime.date(2021, 5, 5)),
        ),
    ]
